Redux react
Bludidi/book-store pull request #3
Opened 2022-11-24 17:36 UTC by Bludidi

2022-11-24 17:44 UTC, thecodechaser commented
@Bludidi Please check slack for my messages.

2022-11-24 18:06 UTC, Danieldotcomcoder reviewed
Hi @Bludidi , 


While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project:
1:  That doesn't include the new professional Readme template , Kindly refer to this [template](https://github.com/microverseinc/readme-template/blob/master/README.md) 👍 👍  to add the new required Readme File 😄 😄.

2: That doesn't include descriptive title and short summary describing introduced changes in more detail inside the Pull Request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-11-25 06:42 UTC, Ismailco reviewed
Hi @Bludidi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has an old README, kindly consider using [the new README template](https://github.com/microverseinc/readme-template) provided by microverse as the previous reviewer mentioned
![Screenshot_20221124_235718](https://user-images.githubusercontent.com/25227022/203916898-0c8eed13-d824-4a2d-9abf-09daabc2fd95.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-11-25 07:53 UTC, brytebee requested changes
Hi, @Bludidi👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- No linter errors.✔️
- The README looks professional.✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 07:53 UTC, brytebee commented on src/App.js
> +import Books from './components/Book';
This error prevents your app from running correctly. Kindly fix it.

![image](https://user-images.githubusercontent.com/27709832/203927271-42b1557f-7692-4ba3-a82e-23eaf9af1c4d.png)

2022-11-25 07:53 UTC, brytebee commented on src/App.js
> +import store from './components/redux/configureStore';
![image](https://user-images.githubusercontent.com/27709832/203928358-73139958-ffc6-4178-b908-8b63dc5bce89.png)

Kindly update your file structure such that `redux` and `components` are directories inside `src` not redux inside `components`. I hope this is clear. Consider the image below:

![image](https://user-images.githubusercontent.com/27709832/203928939-184c0f40-a1ab-4353-b66e-c320a10e9e17.png)

2022-11-25 08:46 UTC, levy002 requested changes
## Hello @Bludidi   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure to correctly import your components.

    ![image](https://user-images.githubusercontent.com/87197412/203938624-ad84e7dd-9bfd-4713-a9e7-f21a3d6a84f9.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 11:11 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Bludidi 

Your project is complete! Great job for making the requested changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- modules well imported
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 11:18 UTC, merged